application: love-notes-777
version: dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on #/_ah/stats/
- remote_api: on #/_ah/remote_api/

handlers:
- url: /.*
  script: main.app
#  secure: always

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
- name: PIL
  version: "latest"

